version: "3.8"

services:
  db:
    image: mysql:5.7
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_USER: "root"
      MYSQL_ROOT_PASSWORD: "12345678"
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: "87654321"

  wordpress:
    depends_on:
      - db
    image: wordpress:latest
    volumes:
      - wordpress_data:/var/www/html
    ports:
      - "8000:80"
    restart: always
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: "87654321"
      WORDPRESS_DB_NAME: wordpress

  exporter:
    depends_on:
    - db
    image: prom/mysqld-exporter
    volumes:
    - ./my.cnf:/my.cnf
    ports:
    - "9104:9104"
    command:
    - "--config.my-cnf=/my.cnf"

volumes:
  db_data: {}
  wordpress_data: {}
  my.cnf:
